### ISSUE TITLE
SD Card link returns 'Not Found'

### ISSUE THREAD

**Issue by SimonFD** [ikjordan/picozx81#22]
Clicking on the link to download an SD card image the browser returns a 'Not Found' message.
No file is downloaded.
Is there an updated link ?

**Comment by ikjordan** [comment]
What link did you click please? 
There is no direct link to a zipped SD Card image, instead a formatted SD Card can be populated with the contents at https://github.com/ikjordan/picozx81/tree/main/examples

One way to do this would be to download the zip file from the latest release: https://github.com/ikjordan/picozx81/archive/refs/tags/v1.0.2.zip
and then to copy the contents of the zip from `examples` into the root of a formatted SDCard

**Comment by ikjordan** [comment]
Updated Readme with corrected link (and images of a ZX80 based replica) now pushed

**Comment by SimonFD** [comment]
Thanks for the swift response and the file :)
