### ISSUE TITLE
SD Card don’t work on Olimex Board

### ISSUE THREAD

**Issue by galluslongus** [ikjordan/picozx81#32]
Hi,
I bought a Olimex board and flashing went well. I do have the zx81 screen but can’t access the sd-card. I tried different ones, no success. Are there different boards outside?

**Comment by ikjordan** [comment]
Hi,
Thanks for raising this:
1) What version and size of SD Card are you using please?
2) When you press F2 to access the SD Card, do you get the message "SD Card Not detected Press New Line to Continue"?

If you have the zx81 screen it sounds like you have a supported board. I'd suggest trying the Olimex SD Card example to see if that uf2 can read and write to the SD Card:
[Olimex example code](https://github.com/OLIMEX/RP2040-PICO-PC/tree/main/SOFTWARE/no-OS-FatFS-SD-SPI-RPi-Pico/simple_example)
[Pre-built binary](https://github.com/OLIMEX/RP2040-PICO-PC/blob/main/SOFTWARE/Prebuilt-UF2/SD_Card.uf2)

**Comment by galluslongus** [comment]
Hi,
thanks for quick replay...

im using a 16 and a 32 GB Card, formated with fat32 and also a small amount with 512 MB with fat16, no success.
Yes, F2 shows the message "SD Card Not detected Press New Line to Continue". I can access al F Keys and also can typ in a Basic Program. Its all working accept the SD Card.

Thanks for the Links, ill test this out.

**Comment by galluslongus** [comment]
so, i checked the pre configured files. DVI shows a Picture with paralax scrolling but SD doesnt do anything. Maybe i have to order a new one just for testing.

**Comment by ikjordan** [comment]
You have tried several SD Cards with the Olimex demo code. Therefore I think you are entitled to return the board as defective. I do know several people with Olimex boards who have used the SD Card successfully, so it sounds like your board may have a manufacturing fault.

**Comment by galluslongus** [comment]
Yeah, I have probed all sd card pins and they should be fine, I don't know. I just ordered a new one, will arrive on Friday, so I need to wait.
I will let you know, thanks so far...

**Comment by galluslongus** [comment]
![IMG_7126](https://github.com/ikjordan/picozx81/assets/32772569/c19c1833-9508-4a1e-a30e-7af28a4659f6)
Heyho,
Unbelievable but true, there was a little solder Bridge at the Pico Board wich shorted two Pins on the Microcontroller.
I got my new ordered OLIMEX Board today and had the same behavior like withe the other one, so i checkt both Bords again with probing and inspecting with a magnifying glass and by accident i saw the mistake at the Pico board. I swapped them and Hurray, i was able to see the SD-Card.
So, everything works fine now...time to Build the Original Keyboard and put it all in a printed ZX80 Case. The reason why i make it. 
Thanks for your Support

**Comment by ikjordan** [comment]
They look excellent!

**Comment by ikjordan** [comment]
If the Mac and Windows VM is identifying a keyboard then it sound like the keyboard code is running correctly. Have you used the 5 and 8 way molex connectors to connect the keyboard? The output from the connectors need to be connected to the Pico GPIO pins. The 5 way connector goes to GP 0 to 4. The 8 way connector goes to GP 5  to12. You can check that there is some connection by using a male to male jumper across the connectors to short together one row and column.
Can you provide a picture of the keyboard wiring please?

**Comment by ikjordan** [comment]
It looks like adafruit may have changed the link I originally gave, which makes things a bit difficult to follow.

Inside the lib directory you need to have copied the directory containing the adafruit_hid library as well as the adafruit_matrixkeypad.mpy file.

Instructions for how to do get the adafruit_hid library are now [here](https://learn.adafruit.com/pico-four-key-macropad/installing-libraries)

**Comment by galluslongus** [comment]
I now have keys, awesome, but a wrong order.
Soldering from left to right from keyboard to gpio0 to gpio12 ?

**Comment by ikjordan** [comment]
It's probably easier to just edit the contents of lines 14 and 15 in code.py, rather than resolder. The fix will probably be to either reverse the order of the pins in line 14, or line 15, or both :-)

**Comment by galluslongus** [comment]
Its working now, had to resolder some lines. But now i need to sleep, have to get up in 5 hours...

**Comment by ikjordan** [comment]
I'm glad it is now working.

My apologies. I opened up my keyboard today and saw that I'd adjusted the wiring order, so that the program could use consecutive row pins. I've now rewired my keyboard to be consecutive and changed the [code.py](https://github.com/ikjordan/ZX81_USB_KBD/blob/main/code.py) file to match the order you give above. 
I've also updated the [Readme](https://github.com/ikjordan/ZX81_USB_KBD/blob/main/README.md) for the project to add the extra info we found out during this exercise:

1. Installation of adafruit_hid library
2. Diagram of directory structure on the Pico, showing all files required
3. Image of case with wiring

Thanks for your help!

**Comment by galluslongus** [comment]
Yeah, the Readme looks good. Now, everyone should be able to install and assemble it easily.
Thats a very cool project, thanks for sharing this with everyone.
I will post some pictures when i finished my Pico ZX80/81.
Cheers, Michael

**Comment by ikjordan** [comment]
If you have any more pictures, it would be great to see them :-)

**Comment by galluslongus** [comment]
I'll finish my zx80 this weekend and will post some more pictures.

**Comment by galluslongus** [comment]
![IMG_7518](https://github.com/ikjordan/picozx81/assets/32772569/ca129371-e734-4e22-a923-273664412b09)
![IMG_7522](https://github.com/ikjordan/picozx81/assets/32772569/f51cc7ec-ae52-49c6-a46d-b0e2d0cd3d5f)
![IMG_7524](https://github.com/ikjordan/picozx81/assets/32772569/781a16ce-f702-4914-8331-da5a6cfa051e)
![IMG_7534](https://github.com/ikjordan/picozx81/assets/32772569/23138878-7852-4e9a-bd98-25e1ce736ab5)
![IMG_7541](https://github.com/ikjordan/picozx81/assets/32772569/2c1c1a24-3c47-4b1c-90a2-caacd42e6a61)
![IMG_7542](https://github.com/ikjordan/picozx81/assets/32772569/c5bcb4e6-807a-44e5-a2ba-dbd6344b13c9)
![IMG_7543](https://github.com/ikjordan/picozx81/assets/32772569/fb47917f-1c8d-4277-a009-60dd503efdf0)
![IMG_7548](https://github.com/ikjordan/picozx81/assets/32772569/35e14ae8-ed11-4ce2-b354-f5f5e7481c1c)

**Comment by galluslongus** [comment]
Heres a few pictures of my ZX80/81 Clone fully working.
Thank you one more time for sharing this project.

**Comment by galluslongus** [comment]
Of course, fell free...

**Comment by ikjordan** [comment]
Thanks, I'll update the Readme when I make the next release. Feel free to add more pictures here ;-)
The next step in the development is to add Chroma compatible vsync sound, and an option to have realistic load and save screens, with audio. Then we can (optionally) re-create the 5 to 10 minute cassette save and load times from when we were kids!

**Comment by ikjordan** [comment]
I've now made the next release. This release supports ZX80 hardware more accurately. It also allows selection of the 4K or 8K ZX80 ROM. Given that you have shown images of both 4K and 8K ROM ZX80s, I hope this is useful! Of course, you can still select ZX81, if you like a steady display :-)

**Comment by galluslongus** [comment]
That’s awesome, I’ll try it tomorrow coz I have a couple days off.
I’ll also check if I find some more interesting pictures.

**Comment by ikjordan** [comment]
Hi - did you find any more pictures to share, or should we close this issue?
Thanks
